<?php

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 *
 * Don't display built-in layouts.
 */
function wcl_layouts_plugin_filter_layout__layout_builder_alter(array &$definitions, array $extra) {
  $overwrite_layouts = [
    'layout_onecol',
    'layout_twocol_section',
    'layout_threecol_section',
    'layout_fourcol_section',
  ];
  $providers = [
    'layout_discovery',
    'layout_builder',
  ];
  // Remove standard Layout Builder / Layout Discovery layouts.
  foreach ($overwrite_layouts as $overwrite_layout) {
    /** @var \Drupal\Core\Layout\LayoutDefinition[] $definitions */
    if (isset($definitions[$overwrite_layout])) {
      if (in_array($definitions[$overwrite_layout]->getProvider(), $providers)) {
        unset($definitions[$overwrite_layout]);
      }
    }
  }
}
