<?php

/**
 * @file
 * Viewer module file.
 */

/**
 * Implements hook_page_attachments().
 */
function viewer_page_attachments(array &$attachments) {
  \Drupal::service('viewer.module')->getPageAttachments($attachments);
}

/**
 * Implements hook_mail().
 */
function viewer_mail($key, &$message, $params) {
  \Drupal::service('viewer.module')->getMail($key, $message, $params);
}

/**
 * Implements hook_theme().
 */
function viewer_theme() {
  return \Drupal::service('viewer.module')->getTheme();
}

/**
 * Implements hook_preprocess_html().
 */
function viewer_preprocess_html(&$page) {
  \Drupal::service('viewer.module')->getPreprocessHtml($page);
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function viewer_theme_suggestions_viewer_plugin_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'viewer_' . $variables['viewer']->getViewerPluginId() . '__' . $variables['viewer']->id();
}

/**
 * Implements hook_cron().
 */
function viewer_cron() {
  \Drupal::service('viewer.cron')->processQueue();
}

/**
 * Viewer import frequency field options.
 */
function viewer_import_frequencies() {
  return \Drupal::service('viewer.module')->getImportFrequencies();
}

/**
 * Viewer plugin preprocess function.
 */
function viewer_viewer_plugin_preprocess(&$variables) {
  \Drupal::service('viewer.module')->getViewerPluginPreprocess($variables);
}
