stages:
  - deploy

deploy_to_dev:
  stage: deploy
  script:
    - ssh argyllbuteinspir@172.25.98.143 -p 2020 "cd public_html;git pull"
  environment:
    name: dev site
    url: https://argyll-bute.inspireserverc.com/
  only:
    - devel
