<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter()
 * 
 * @param type $form
 * @param FormStateInterface $form_state
 * @param type $form_id
 */
function hide_user_fields_form_alter(&$form, FormStateInterface $form_state, $form_id) { {
    if ($form_id == 'user_form') {
      if (\Drupal::currentUser()->hasPermission('edit hidden user fields')) {
        $form['field_editor_newsrooms']['#access'] = TRUE;
        // add other fields here
      }
      else {
        $form['field_editor_newsrooms']['#access'] = FALSE;
        // add other fields here
      }
    }
  }
}
