services:
  plugin.manager.prod_check:
    class: Drupal\prod_check\Plugin\ProdCheckPluginManager
    parent: default_plugin_manager
  plugin.manager.prod_check_processor:
    class: Drupal\prod_check\Plugin\ProdCheckProcessorPluginManager
    parent: default_plugin_manager
  plugin.manager.prod_check_categories:
    class: Drupal\prod_check\Plugin\ProdCheckCategoryPluginManager
    arguments: ['@module_handler', '@cache.discovery']
    tags:
      - { name: plugin_manager_cache_clear }
