prod_check.report:
  title: 'Production check'
  parent: system.admin_reports
  description: 'View the Production check report page.'
  route_name: prod_check.report
prod_check.settings:
  title: 'Production check'
  description: 'Production check settings.'
  route_name: prod_check.admin_settings
  parent: system.admin_config_system
