prod_check.report:
  path: '/admin/reports/prod-check'
  defaults:
    _controller: '\Drupal\prod_check\Controller\StatusReportController::build'
    _title: 'Production check'
  requirements:
    _permission: 'access production check'
prod_check.admin_settings:
  path: 'admin/config/system/prod-check'
  defaults:
    _form: '\Drupal\prod_check\Form\SettingsForm'
    _title: 'Production check settings'
  requirements:
    _permission: 'administer production check'

entity.prod_check_processor.collection:
  path: '/admin/config/system/prod-check/processors'
  defaults:
    _title: 'Production check processors'
    _entity_list: 'prod_check_processor'
  requirements:
    _permission: 'administer production check'
entity.prod_check_processor.edit_form:
  path: '/admin/config/system/prod-check/processors/configure/{prod_check_processor}'
  defaults:
    _entity_form: 'prod_check_processor.edit'
    _title: 'Configure'
  requirements:
    _permission: 'administer production check'

entity.prod_check.collection:
  path: '/admin/config/system/prod-check/checks'
  defaults:
    _title: 'Production checks'
    _entity_list: 'prod_check'
  requirements:
    _permission: 'administer production check'
entity.prod_check.edit_form:
  path: '/admin/config/system/prod-check/checks/configure/{prod_check}'
  defaults:
    _entity_form: 'prod_check.edit'
    _title: 'Configure'
  requirements:
    _permission: 'administer production check'
entity.prod_check.disable:
  path: '/admin/config/system/prod-check/checks/configure/{prod_check}/disable'
  defaults:
    _entity_form: 'prod_check.disable'
    _title: 'Disable production check'
  requirements:
    _entity_access: 'prod_check.disable'
entity.prod_check.enable:
  path: '/admin/config/system/prod-check/checks/configure/{prod_check}/enable'
  defaults:
    _entity_form: 'prod_check.enable'
    _title: 'Enable production check'
  requirements:
    _entity_access: 'prod_check.enable'
