name: 'Production Check'
type: 'module'
description: "Check a site to see if it's properly setup for production use."
package: Monitoring
core_version_requirement: ^8.8 || ^9
configure: prod_check.report

# Information added by Drupal.org packaging script on 2021-09-09
version: '8.x-1.0-alpha8'
project: 'prod_check'
datestamp: 1631179992
