prod_check.settings_tab:
  route_name: prod_check.admin_settings
  title: Settings
  base_route: prod_check.settings_tab
  weight: 0
prod_check.checks_tab:
  route_name: entity.prod_check.collection
  title: Production checks
  base_route: prod_check.settings_tab
  weight: 10
prod_check.processors_tab:
  route_name: entity.prod_check_processor.collection
  title: Processors
  base_route: prod_check.settings_tab
  weight: 20
