'access production check':
  'title': "Access Production check's status page"
  'description': 'View the report on all checks performed by Production check.'
'administer production check':
  'title': 'Administer production check'
  'description': 'Configure Production Check settings.'
