'settings':
  'title': 'Settings'
  'description': 'Checks wether various settings are fit for a production environment.'
'server':
  'title': 'Server'
  'description': 'Checks certain server side parameters such as APC.'
'performance':
  'title': 'Performance'
  'description': 'Checks if performance settings are OK for production use.'
'security':
  'title': 'Security'
  'description': 'Various security related checks.'
'modules':
  'title': 'Modules'
  'description': "Checks if certain modules are on or off and if they're properly configured."
'seo':
  'title': 'SEO'
  'description': 'Checks if basic SEO modules are enabled.'
'prod_mon':
  'title': 'Production monitor'
  'description': 'Specific checks that only work with Production monitor!'
