<?php

/**
 * @file
 * Contains userswitch.module.
 */

use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_help().
 */
function userswitch_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.userswitch':
      return t('The User Switch module allows the user to switch accounts.');
  }
}

/**
 * Implements hook_entity_operation_alter().
 */
function userswitch_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if ($entity instanceof UserInterface && $entity->isActive() && $entity->id() !== \Drupal::currentUser()->id()) {
    // Alter the title and weight.
    $operations['userswitch'] = [
      'title' => t('Switch user'),
      'weight' => 15,
      'url' => Url::fromRoute('userswitch.user.switch', ['user' => $entity->id()]),
    ];
  }
}

/**
 * Implements hook_toolbar().
 */
function userswitch_toolbar() {
  $items = [];
  if (\Drupal::service('userswitch')->isSwitchUser()) {
    $items['user_switch_back'] = [
      '#type' => 'toolbar_item',
      'tab' => [
        '#type' => 'link',
        '#title' => t('Back to Account'),
        '#url' => Url::fromRoute('userswitch.backuser.switch'),
        '#attributes' => [
          'class' => ['toolbar-icon', 'toolbar-icon-escape-admin'],
        ],
      ],
      '#weight' => -20,
    ];
  }
  return $items;
}
