name: 'Production Check XML-RPC'
type: 'module'
description: "Exposes the prod check report as an XML-RPC service"
package: Monitoring
core_version_requirement: ^8.9 || ^9
configure: entity.prod_check_processor.collection
dependencies:
  - prod_check:prod_check
  - xmlrpc:xmlrpc

# Information added by Drupal.org packaging script on 2023-05-04
version: '2.0.0-beta1'
project: 'prod_check'
datestamp: 1683208857
