# Schema for the configuration files of the Production check module.

prod_check.settings:
  type: mapping
  label: 'Production check settings'
  mapping:
    site_email:
      type: string
      label: 'The base email for the site'

prod_check.prod_check_processor.*:
  type: config_entity
  label: 'Prod check processor'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    plugin:
      type: string
      label: 'Plugin'
    configuration:
      type: prod_check_processor.configuration.[%parent.plugin]

prod_check.prod_check.*:
  type: config_entity
  label: 'Prod check'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    plugin:
      type: string
      label: 'Plugin'
    configuration:
      type: prod_check.configuration.[%parent.plugin]

prod_check_config:
  type: mapping
  label: 'Basic prod check config'
  mapping:
    severity:
      type: integer
      label: 'Severity'

prod_check.configuration.*:
  type: prod_check_config

prod_check.configuration.release_notes:
  type: prod_check_config
  label: 'Release notes settings'
  mapping:
    files:
      type: sequence
      label: 'Files to check'
      sequence:
        - type: string
          label: 'File'

prod_check.configuration.user_register:
  type: prod_check_config
  label: 'User registration settings'
  mapping:
    options:
      type: sequence
      label: 'The user registration option'
      sequence:
        - type: string
          label: 'Option'
